#!/bin/bash
#
# Install Homebrew
set -e

echo "Installing Homebrew"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Fetch dependencies
echo "Installing dependencies"
brew install git
git clone https://github.com/surminus/dotfiles.git ~/.dotfiles
brew bundle --file ~/.dotfiles/Brewfile

# Create my development environment
mkdir ~/surminus

echo "Fetching setup scripts"
git clone https://github.com/surminus/setup.git ~/surminus/setup

# Configure MacOS
echo "Configuring Dock"
~/surminus/setup/osx

# Setup Shell
echo "Setting up Shell"
sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-completions ~/.oh-my-zsh/custom/plugins/zsh-completions

echo "Creating dotfiles"
~/.dotfiles/bin/setup install

echo "Fetching Vundle for Vim"
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

# Add aws-tools
git clone https://github.com/surminus/aws-tools ~/surminus/aws-tools
ln -s ~/surminus/aws-tools/awsexport /usr/local/bin/awsexport

echo "Configuring GPG"
echo "pinentry-program /usr/local/bin/pinentry-mac" >> ~/.gnupg/gpg-agent.conf
echo "use-standard-socket" >> ~/.gnupg/gpg-agent.conf

cat << EOF
  You will need to do the following before we can really get going:
  1. Install your GPG key
  2. Log into Github
  3. Generate an SSH key: ssh-keygen -b 4096
  4. Add your SSH key to your Github account.

  Use your flash drive to complete these steps.

  When this is done, run:

  git clone git@github.com:surminus/pass.git ~/.password-store

  When this is complete, you should almost be set!

  Remember to install vim plugins:
  vim +PluginInstall +qall
EOF
