#!/bin/bash
#
# Install Homebrew
echo "Installing Homebrew"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Setup Shell
echo "Setting up Shell"
brew install git
brew install wget
brew install zsh
sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

echo "Creating dotfiles"
git clone git@github.com:surminus/dotfiles.git ~/.dotfiles
~/.dotfiles/bin/setup install

echo "Setting up Vim"
brew install vim --with-luajit
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall

# Create my development environment
mkdir ~/surminus

# Add aws-tools
git clone https://github.com/surminus/aws-tools ~/surminus/aws-tools
ln -s ~/surminus/aws-tools/awsexport /usr/local/bin/awsexport

echo "Download Chrome"
open https://www.google.com/intl/en/chrome/

# Setup my passwords
echo "Installing pass"
brew install pass

cat << EOF
  You will need to do the following before we can really get going:
  1. Install your GPG key
  2. Log into Github
  3. Add your SSH key to your Github account.

  Use your flash drive to complete these steps.

  When this is done, run:

  git clone git@github.com:surminus/pass.git ~/.password-store

  When this is complete, you should almost be set!

  Useful links to follow:

  Slack: https://slack.com/downloads/osx
  Docker: https://docs.docker.com/docker-for-mac/install/
EOF
